version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: radar-cobmais-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - radar-cobmais

  nginx:
    image: nginx:alpine
    container_name: radar-cobmais-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - radar-cobmais

  db:
    image: mysql:8.0
    container_name: radar-cobmais-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - radar-cobmais

networks:
  radar-cobmais:
    driver: bridge 